[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_one"
path = "src/day_one/bin/main.rs"

[[bin]]
name = "day_two"
path = "src/day_two/bin/main.rs"

[dependencies]
regex = "1.10.2"
log = "0.4.20"
env_logger = "0.7.1"
